# Generated by Django 5.2 on 2025-04-30 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="raw", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Questionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveSmallIntegerField()),
                ("normal_hearing", models.BooleanField()),
                ("approve", models.BooleanField()),
                ("first_time", models.BooleanField()),
                ("first_language", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Stimulus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.IntegerField()),
                ("label", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="din.questionary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("answer", models.CharField(max_length=3)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="din.experiment"
                    ),
                ),
                (
                    "stimulus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="din.stimulus"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="din", max_length=100)),
                ("language", models.CharField(default="nl", max_length=2)),
                ("n_questions", models.PositiveSmallIntegerField(default=24)),
                ("starting_level", models.IntegerField(default=0)),
                ("increment", models.IntegerField(default=2)),
                ("min_level", models.IntegerField(default=-20)),
                ("max_level", models.IntegerField(default=10)),
                ("n_stimuli", models.IntegerField(default=128)),
                (
                    "audio_generator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="din.audiogenerator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stimulus",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="din.test"
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="din.test"
            ),
        ),
    ]
